name: CD

on:
  push:
    branches:
      - 'main'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Build image'
        run: docker build -t data-dashboard .

      - name: 'Run container'
        run: docker run -p 8080:80 -d --rm --name data-dashboard data-dashboard

      - name: 'Verify container'
        run: |
          curl -O https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          ./wait-for-it.sh -t 20 localhost:8080

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push docker image - extension
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            fraunhoferiosb/edc-extension4aas-dashboard:latest
            fraunhoferiosb/edc-extension4aas-dashboard:0.1.0
